### ISSUE TITLE
fits header key 'date-obs' not preserved

### ISSUE THREAD

**Issue by gica3618** [richteague/bettermoments#16]
It looks like the 'date-obs' keyword in the headers of the moment 0 maps are set to some default value (1858/11/17/00:00:00). Would it be possible to pass along the 'date-obs' from the header of the input cube to the header of the output moment 0 maps?
It wonder where this 1858/11/17/00:00:00 date comes from. Maybe this is astropy's `fits.writeto` with `output_verify='silentfix'`? However, I tried `output_verify='exception'`, and it still put that default date into the header without raising an exception.

**Comment by richteague** [comment]
This all comes about from the `_write_header` function in `io.py`. I think my original intent was to have a very cleaned out header and just include the information that was needed, but perhaps it would just be easier to copy the old header and clean out the spectral coordinate stuff?

**Comment by gica3618** [comment]
Ok now I realised that this is actually a problem of CASA's `imhead`. If I check the headers with astropy, the 'date-obs' keyword is not there, which is fine. But reading the header with `imhead`, it says that 'date-obs' equals 1858/11/17/00:00:00. So `imhead` just seems to insert a default value if the keyword is not there. I guess I will have to talk to the CASA people about that...
