### ISSUE TITLE
command line option 'outname' is ignored

### ISSUE THREAD

**Issue by gica3618** [richteague/bettermoments#17]
After installing the newest version 1.6.1, it looks like the -outname option is ignored. In other words, even when specifying -outname, the output moment 0 maps' names are based on the input cubes' names. Furthermore, they are saved in the same directory as the input cube, so it seems no longer possible to specify the location where the output maps should be saved.

**Comment by richteague** [comment]
Good catch! Should be solved by https://github.com/richteague/bettermoments/commit/bc626688962de7b11fa67c57f5754118e8d97e1f
