### ISSUE TITLE
Error without outname option in command line

### ISSUE THREAD

**Issue by yyamato-as** [richteague/bettermoments#18]
Dear Rich,

I installed the latest version and run in command-line without `-outname` option, but I got an error saying `AttributeError: 'str' object has no attribute 'copy'` at line 264 in `io.py`. Maybe `path.copy()` should be simply `path` ?

**Comment by richteague** [comment]
Thanks for spotting this! I have pushed a fix: https://github.com/richteague/bettermoments/commit/f923f3739aab58c7423547d1de7f268c6591162c.
