### ISSUE TITLE
Channel width in the zeroth moment maps

### ISSUE THREAD

**Issue by shengjunlin** [richteague/bettermoments#23]
I think the variable `chan` in `methods.collapse_zeroth` should be a positive value in case that `velax` is a decreasing sequence, i.e.,
```
chan = abs(np.diff(velax).mean())
```
Otherwise, the zeroth moment values (`M0`) and their uncertainties (`dM0`) will have opposite signs.

**Comment by richteague** [comment]
Thanks! I've fixed this in `v1.8.7`.
