### ISSUE TITLE
installation woes

### ISSUE THREAD

**Issue by teuben** [richteague/bettermoments#5]
would be useful to add an installation note, since imgcube isn't something available in an obvious way. Not via pip, but 
     git clone https://github.com/richteague/imgcube 
inside of the notebooks directory make it work.

Had to comment out the plt.style.use('paper') My anaconda didn't have it. Now looks awfully small, what's the trick to get it working with 'paper' option?

**Comment by richteague** [comment]
I've included a new function, `data_from_fits` which will extract the necessary values from the cube without having to call the `imgcube` function. This should mean that you can still pip install.

I've also removed `plt.style.use('paper')` from the Notebook as that was just used to set the styles for making the plots. This should now default to whatever default the user has.

**Comment by teuben** [comment]
I should revisit the fits ingestion in both cases, as I only got a correct comparison if i shifted the pixels by 1 comparing yours and mine. It's an easy thing to miss, using 0 based or 1 based... I'd like to think mine is correct. If you feel your is correct too, we should revisit.  I'll redo mine with your new function and open a new issue if need be.

**Comment by richteague** [comment]
I compared the results with the values which are given when I load up the file in CASA. It shows that the first and last channels have velocity of 2.5km/s and 11.158km/s which are the same as I have in the second cell of moment-comparison.ipynb.

I have to admit, I’m not sure whether the value is defined at the start of the channel, center or end which might cause an issue.

**Comment by teuben** [comment]
Oh, i meant positional pixels, not spectrally.  As for the fits definition: the value is defined at the center of the pixel, where the first pixel is 1.  But let me redo the comparison with your new function and it should be more clear.

**Comment by richteague** [comment]
Ah yeah, that makes sense. I didn't really do this very thoroughly as typically people may want to handle their coordinates in different ways, for example using Astropy's WCS package.
